apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
      name: blog
    spec:
      containers:
      - image: "ftzm/blog:0.1.2-d22ed1d649"
        name: blog
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: blog
spec:
  ports:
  - port: 80
  selector:
    app: blog

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: blog
spec:
  rules:
  - host: blog.fitzsimmons.io
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: 80
  - host: www.fitzsimmons.io
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: 80
  - host: fitzsimmons.io
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: 80
  tls:
  - secretName: "blog-crt-secret"

---
apiVersion: "cert-manager.io/v1alpha2"
kind: Certificate
metadata:
  name: blog
spec:
  dnsNames:
  - blog.fitzsimmons.io
  - www.fitzsimmons.io
  - fitzsimmons.io
  issuerRef:
    group: "cert-manager.io"
    kind: ClusterIssuer
    name: "letsencrypt-prod"
  secretName: "blog-crt-secret"
