apiVersion: apps/v1
kind: Deployment
metadata:
  name: typespeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typespeed
  template:
    metadata:
      labels:
        app: typespeed
      name: typespeed
    spec:
      containers:
      - image: "ftzm/typespeed:a4fdde28f2"
        name: typespeed
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: typespeed
  name: typespeed
spec:
  ports:
  - port: 80
  selector:
    app: typespeed

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: typespeed
spec:
  rules:
  - host: typespeed.fitzsimmons.io
    http:
      paths:
      - backend:
          serviceName: typespeed
          servicePort: 80
  tls:
  - secretName: "typespeed-crt-secret"

---
apiVersion: "cert-manager.io/v1alpha2"
kind: Certificate
metadata:
  name: typespeed
spec:
  dnsNames:
  - typespeed.fitzsimmons.io
  issuerRef:
    group: "cert-manager.io"
    kind: ClusterIssuer
    name: "letsencrypt-prod"
  secretName: "typespeed-crt-secret"
